### ISSUE TITLE
make it faster bruh

### ISSUE THREAD

**Issue by LocalSmail** [Smug246/Luna-Nuker#5]
like that one guy said, make it faster 💀💀💀💀💀

**Comment by SlepPoweredBy2** [comment]
bro are u making it faster or not u lazy ass bitch

@Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246 @Smug246
